<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>no title</title>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    	<a class="navbar-brand" href="#">博客平台后台管理</a>
    	<ul class="nav navbar-nav">
    		<li class="active">
    			<a href="#">Home</a>
    		</li>
    		<li>
    			<a href="#">Link</a>
    		</li>
    	</ul>
    </nav>

    <div class="container-fluid" style="min-height: 500px;">

        <div class="row">

        	<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="row">
                	<div class="list-group">
                		<a href="#" class="list-group-item active">Item 1</a>
                		<a href="#" class="list-group-item">Item 2</a>
                		<a href="#" class="list-group-item">Item 3</a>
                	</div>
                </div>
        	</div>

            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <?php echo $this->content; ?>
            </div>

        </div>

    </div>


    <div class="panel panel-default">
    	  <div class="panel-footer">
    			@2016 Lamkakyun All Rights Reserved.
    		</div>
    </div>

</body>
</html>